changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Terminology and Value Sets
      labels:
        - terminology
    - title: Connectors
      labels:
        - connector
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
