name: 'the_tuva_project'
version: '0.14.12'
config-version: 2
require-dbt-version: ">=1.5.0"

profile: default

models:
  the_tuva_project:
    +materialized: view 

seeds:
  the_tuva_project:
    +materialized: table

# Default dbt settings
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["dbt_doc_blocks"]
target-path: "target"

clean-targets:
    - "target"
    - "dbt_packages"
  