name: 'the_tuva_project'
version: '0.8.0'
config-version: 2
require-dbt-version: ">=1.3.0"


profile: default

vars:

    ## CCSR data mart vars
    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "'2023.1'"
    prccsr_version: "'2023.1'"


    ## CMS HCC data mart vars
    # The payment_year variable has a default of the current year, this can be
    # changed by adding the numeric value of a year (ex: cms_hcc_payment_year: 2019)
    cms_hcc_payment_year: '{{ run_started_at.strftime("%Y") }}'


    ## Quality Measures period var
    # to run quality measueres for a period other than current year, add the below variable uncommented to your project
    # quality_measures_period_end: "2020-12-31"


    ## Tuva Last Run
    # The date and timestamp of the dbt run that will populate the tuva_last_run column in all models.
    # Default timezone is UTC
    tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  the_tuva_project:
    terminology:
      terminology__calendar:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','calendar.csv',compression=true,null_marker=true) }}"
      terminology__hcpcs_level_2:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','hcpcs_level_2.csv',compression=true,null_marker=true) }}"
      terminology__icd_10_pcs:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','icd_10_pcs.csv',compression=true,null_marker=true) }}"
      terminology__icd_10_cm:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','icd_10_cm.csv',compression=true,null_marker=true) }}"
      terminology__icd_9_cm:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','icd_9_cm.csv',compression=true,null_marker=true) }}"
      terminology__loinc:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','loinc.csv',compression=true,null_marker=true) }}"
      terminology__loinc_deprecated_mapping:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','loinc_deprecated_mapping.csv',compression=true,null_marker=true) }}"
      terminology__other_provider_taxonomy:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','other_provider_taxonomy.csv',compression=true,null_marker=true) }}"
      terminology__ndc:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','ndc.csv',compression=true,null_marker=true) }}"
      terminology__provider:
        +post-hook: "{{ load_seed('tuva-public-resources/provider_data','provider.csv',compression=true,null_marker=true) }}"
      terminology__rxnorm_to_atc:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','rxnorm_to_atc.csv',compression=true,null_marker=true) }}"
      terminology__snomed_icd_10_map:
        +post-hook: "{{ load_seed('tuva-public-resources/terminology','snomed_icd_10_map.csv',compression=true,null_marker=true) }}"
    value_sets:
      ccsr:
        ccsr__dxccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','dxccsr_v2023_1_cleaned_map.csv',compression=true,null_marker=true) }}"
        ccsr__prccsr_v2023_1_cleaned_map:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','prccsr_v2023_1_cleaned_map.csv',compression=true,null_marker=true) }}"
      chronic_conditions:
        chronic_conditions__cms_chronic_conditions_hierarchy:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','cms_chronic_conditions_hierarchy.csv',compression=true,null_marker=true) }}"    
      cms_hcc:
        cms_hcc__cpt_hcpcs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','cpt_hcpcs.csv',compression=true,null_marker=true) }}"
        cms_hcc__icd_10_cm_mappings:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','cms_hcc_icd_10_cm_mappings.csv',compression=true,null_marker=true) }}" 
      ed_classification:
        ed_classification__icd_10_cm_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_cm_to_ccs.csv',compression=true,null_marker=true) }}"
        ed_classification__johnston_icd10:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','johnston_icd10',compression=true,null_marker=true) }}"
        ed_classification__johnston_icd9:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','johnston_icd9',compression=true,null_marker=true) }}"
      hcc_suspecting:
        hcc_suspecting__icd_10_cm_mappings:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','hcc_suspecting_icd_10_cm_mappings.csv',compression=true,null_marker=true) }}" 
      readmissions:
        readmissions__icd_10_pcs_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_pcs_to_ccs.csv',compression=true,null_marker=true) }}"
        readmissions__icd_10_cm_to_ccs:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','icd_10_cm_to_ccs.csv',compression=true,null_marker=true) }}"
      clinical_concept_library:
        clinical_concepts:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','tuva_clinical_concepts.csv',compression=true,null_marker=true) }}"
        value_set_members:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','tuva_value_set_members.csv',compression=true,null_marker=true) }}"
        coding_systems:
          +post-hook: "{{ load_seed('tuva-public-resources/value-sets','tuva_coding_systems.csv',compression=true,null_marker=true) }}"
