name: 'the_tuva_project'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.5.0"

profile: tuva_v1

models:
  the_tuva_project:
    +materialized: view
    claims_prep:
      +schema: tuva_claims_prep
      encounters:
        +materialized: table
      service_category:
        +materialized: table
    core:
      final:
        +schema: tuva_core
        +materialized: table
      staging:
        +schema: tuva_staging
    input_layer:
      +schema: tuva_input_layer
    marts:
      financial_pmpm:
        +schema: tuva_financial_pmpm
        final:
          +materialized: table
      readmissions:
        +schema: tuva_readmissions
        final:
          +materialized: table


seeds:
  the_tuva_project:
    +materialized: seed

on-run-start: |
  {% if var('enable_tuva_run_log', false) %}
  {{ log_invocation_start() }}
  {% endif %}

# Default dbt settings
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["doc_blocks"]
target-path: "target"

clean-targets:
    - "target"
    - "dbt_packages"
  