name: 'tuva'
version: '0.1.5'
config-version: 2

profile:                # configuration required (your profile to connect dbt to your data warehouse)

vars:
    source_name:        # configuration required (name of your source dataset e.g. cms_claims)
    source_database:    # configuration required (name of the database where your data is stored)
    source_schema:      # configuration required (name of the schema where you created staging tables)

    src_patient: "{{ source(var('source_name'),'stg_patient') }}"
    src_encounter: "{{ source(var('source_name'),'stg_encounter') }}"
    src_diagnosis: "{{ source(var('source_name'),'stg_diagnosis') }}"
    src_procedure: "{{ source(var('source_name'),'stg_procedure') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  tuva:
    +database:          # configuration required (should be the same as source database)
    +schema: tuva

seeds:
  tuva:
    +database:          # configuration required (should be the same as source database)
    +schema: vocabulary
    +tags: vocabulary
    