  default:
    target: ci
    outputs:
      ci:
        type: snowflake
        account: "{{ env_var('DBT_SNOWFLAKE_CI_ACCOUNT') }}"
        warehouse: "{{ env_var('DBT_SNOWFLAKE_CI_WAREHOUSE') }}"
        database: "{{ env_var('DBT_SNOWFLAKE_CI_DATABASE') }}"
        role: "{{ env_var('DBT_SNOWFLAKE_CI_ROLE') }}"
        schema: "{{ env_var('DBT_SNOWFLAKE_CI_SCHEMA') }}"
        user: "{{ env_var('DBT_SNOWFLAKE_CI_USER') }}"
        password: "{{ env_var('DBT_SNOWFLAKE_CI_PASSWORD') }}"
        threads: 5