select 
     cast(concat(med.claim_id, med.data_source) as varchar(100)) as [Claim Header ID]
   , cast(med.claim_line_number as varchar(50)) as [Claim Service Line ID]
   , 0 as [Adjustment Type Code]
   , 0 as [Adjustment Sequence]
   , cast(med.place_of_service_code as varchar(2)) as [Place of Service Type CMS Code]
   , 1 as [Billing Procedure Code Set]
   , cast(med.hcpcs_code as varchar(10)) as [Billing Procedure Code]
   , convert(varchar(8), med.claim_line_start_date, 112) as [Performed Start Date]
   , convert(varchar(8), med.claim_line_end_date, 112) as [Performed End Date]
   , cast(med.hcpcs_modifier_1 as varchar(2)) as [First Modifier]
   , cast(med.hcpcs_modifier_2 as varchar(2)) as [Second Modifier]
   , cast(med.hcpcs_modifier_3 as varchar(2)) as [Third Modifier]
   , cast(med.hcpcs_modifier_4 as varchar(2)) as [Fourth Modifier]
   , cast(med.hcpcs_modifier_5 as varchar(2)) as [Fifth Modifier]
   , cast(null as varchar(2)) as [Sixth Modifier]
   , cast(try_cast(med.rendering_id as bigint) as varchar(10)) as [Rendering Provider NPI]
   , cast(rend.primary_taxonomy_code as varchar(10)) as [Rendering Provider NUCC Taxonomy Code]
   , 1 as [Rendering Provider Specialty Code Set]
   , cast(rend.primary_specialty_description as varchar(10)) as [Rendering Provider Specialty Code]
   , cast(med.service_unit_quantity as numeric) as [Quantity]
   , cast(med.revenue_center_code as varchar(4)) as [Revenue Code]
   , cast(med.charge_amount as numeric) as [Billed Amount]
   , cast(med.allowed_amount as numeric) as [Allowed Amount]
   , cast(med.copayment_amount as numeric) as [Copay Amount]
   , cast(med.coinsurance_amount as numeric) as [Coinsurance Amount]
   , cast(med.deductible_amount as numeric) as [Deductible Amount]
   , cast(null as numeric) as [Not Covered Amount]
   , cast(med.paid_amount as numeric) as [Paid Amount]
   , cast(null as numeric) as [COB Amount]
   , cast(null as varchar(10)) as [Ordering Provider NPI]
   , cast(null as varchar(10)) as [Ordering Provider NUCC Taxonomy Code]
   , cast(null as numeric) as [Ordering Provider Specialty Code Set]
   , cast(null as varchar(10)) as [Ordering Provider Specialty Code]
   , cast(null as varchar(11)) as [NDC]
   , cast(null as numeric) as [NDC Quantity]
   , cast(null as varchar(2)) as [NDC Units]
   , cast(null as varchar(50)) as [Prescription Number]
   , cast(null as varchar(50)) as [Link Sequence Number]
   , 0 as [Is Capitated]
   , 1 as [Line Processing Status]
   , cast(null as varchar(300)) as [Denial Reason]
from {{ ref('core__medical_claim') }} as med
left join {{ ref('terminology__provider') }} rend
    on med.rendering_id = rend.npi
