select
    py.benchmark_key
    ,py.year_nbr
    ,py.person_id
    ,py.payer
    ,py.plan
    ,py.data_source
    ,paid_amount_pred
    ,outpatient_paid_amount_pred
    ,other_paid_amount_pred
    ,office_based_paid_amount_pred
    ,inpatient_paid_amount_pred
    ,outpatient_injections_paid_amount_pred
    ,emergency_department_paid_amount_pred
    ,outpatient_radiology_paid_amount_pred
    ,outpatient_pt_ot_st_paid_amount_pred
    ,outpatient_hospice_paid_amount_pred
    ,urgent_care_paid_amount_pred
    ,outpatient_hospital_or_clinic_paid_amount_pred
    ,home_health_paid_amount_pred
    ,dialysis_paid_amount_pred
    ,outpatient_rehabilitation_paid_amount_pred
    ,outpatient_surgery_paid_amount_pred
    ,ambulatory_surgery_center_paid_amount_pred
    ,outpatient_psych_paid_amount_pred
    ,dme_orphaned_paid_amount_pred
    ,orphaned_claim_paid_amount_pred
    ,ambulance_orphaned_paid_amount_pred
    ,lab_orphaned_paid_amount_pred
    ,office_visit_radiology_paid_amount_pred
    ,office_visit_paid_amount_pred
    ,office_visit_surgery_paid_amount_pred
    ,office_visit_other_paid_amount_pred
    ,telehealth_paid_amount_pred
    ,office_visit_pt_ot_st_paid_amount_pred
    ,office_visit_injections_paid_amount_pred
    ,acute_inpatient_paid_amount_pred
    ,inpatient_hospice_paid_amount_pred
    ,inpatient_psych_paid_amount_pred
    ,inpatient_rehabilitation_paid_amount_pred
    ,inpatient_skilled_nursing_paid_amount_pred
    ,inpatient_count_pred + office_based_count_pred + other_count_pred + outpatient_count_pred as count_pred
    ,inpatient_count_pred
    ,office_based_count_pred
    ,other_count_pred
    ,outpatient_count_pred
    ,outpatient_injections_count_pred
    ,emergency_department_count_pred
    ,outpatient_radiology_count_pred
    ,outpatient_pt_ot_st_count_pred
    ,outpatient_hospice_count_pred
    ,urgent_care_count_pred
    ,outpatient_hospital_or_clinic_count_pred
    ,home_health_count_pred
    ,dialysis_count_pred
    ,outpatient_rehabilitation_count_pred
    ,outpatient_surgery_count_pred
    ,ambulatory_surgery_center_count_pred
    ,outpatient_psych_count_pred
    ,dme_orphaned_count_pred
    ,orphaned_claim_count_pred
    ,ambulance_orphaned_count_pred
    ,lab_orphaned_count_pred
    ,office_visit_radiology_count_pred
    ,office_visit_count_pred
    ,office_visit_surgery_count_pred
    ,office_visit_other_count_pred
    ,telehealth_count_pred
    ,office_visit_pt_ot_st_count_pred
    ,office_visit_injections_count_pred
    ,acute_inpatient_count_pred
    ,inpatient_hospice_count_pred
    ,inpatient_psych_count_pred
    ,inpatient_rehabilitation_count_pred
    ,inpatient_skilled_nursing_count_pred
  FROM {{ source('expected_values','person_year') }} py
  INNER JOIN {{ source('predictions','encounter_predictions')}} p
    ON py.benchmark_key = p.benchmark_key