{{ dq_config_analytical_metric_model('analytical_key_metric__encounter__outpatient_ambulatory_surgery_center') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__encounter__outpatient_ambulatory_surgery_center') }}
