{{ dq_config_analytical_metric_model('analytical_key_metric__encounter__outpatient_outpatient_radiology') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__encounter__outpatient_outpatient_radiology') }}
