{{ dq_config_analytical_metric_model('analytical_key_metric__chronic_condition__type_2_diabetes_mellitus') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__chronic_condition__type_2_diabetes_mellitus') }}
