{{ dq_config_analytical_metric_model('analytical_key_metric__ed_classification__emergent_ed_care_needed_preventable_avoidable') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__ed_classification__emergent_ed_care_needed_preventable_avoidable') }}
