{{ dq_config_analytical_metric_model('analytical_key_metric__medication__respiratory_nucala_mepolizumab') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__medication__respiratory_nucala_mepolizumab') }}
