name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: tuva_prod_powerbi

vars:
  error_empty_seeds: true
  ## Use this variable to run the project with synthetic data loaded as seeds
  # otherwise set to false and set the input vars below
  use_synthetic_data: false

  ## Update these vars to use your own data as input, do not comment out
  # enabled logic has been added to the sources config
  input_database: medicare_lds_five_percent
  input_schema: input_layer

  tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'

  ## The Tuva Project can support claims and clinical data.
  # By default, all models are disabled.
  # Use the vars below to enabled or disable sections of The Tuva Project.

  ## The vars directly below enable all models related to the type of healthcare data being used
  clinical_enabled: false
  claims_enabled: true
  provider_attribution_enabled: false


  ## CMS HCC data mart vars
  # The payment_year variable has a default of the current year, this can be
  # changed by adding the numeric value of a year (ex: cms_hcc_payment_year: 2019)
  # cms_hcc_payment_year: 2018


  ## Quality Measures period var
  # to run quality measueres for a period other than current year, add the below variable uncommented to your project
#  quality_measures_period_end: "2018-12-31"

  ## The vars directly below enable a single data mart.  See the Quickstart
  # guide for instructions.

  # ccsr_enabled: false
  # cms_chronic_conditions_enabled: false
  # tuva_chronic_conditions_enabled: false
  # claims_preprocessing_enabled: false
  # cms_hcc_enabled: false
  # ed_classification_enabled: false
  # financial_pmpm_enabled: false
  # insights_enabled: false
  # quality_measures_enabled: false
  # readmissions_enabled: true


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


dispatch:
  - macro_namespace: 'the_tuva_project'
    search_order: ['integration_tests','the_tuva_project']


seeds:
  integration_tests:
    eligibility_seed:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.13.0','eligibility.csv',headers=true) }}"
    lab_result_seed:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.13.0','lab_result.csv',headers=true) }}"
    medical_claim_seed:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.13.0','medical_claim.csv',headers=true) }}"
    observation_seed:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.13.0','observation.csv',headers=true) }}"
    pharmacy_claim_seed:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.13.0','pharmacy_claim.csv',headers=true) }}"
    provider_attribution_seed:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.13.0','provider_attribution.csv',headers=true) }}"

models:
  integration_tests:
    +materialized: ephemeral
