name: 'tuva_integration_tests'
version: '0.1.1'
config-version: 2
require-dbt-version: ">=1.5.0"

profile: tuva_v1

models:
  tuva_integration_tests:
    input_layer:
      +schema: tuva_input_layer
      +materialized: view
vars:
  use_synthetic_data: false # if true, will use synthetic data from tuva_data_assets instead of the source below.
  source_database: tuva_v1
  source_schema: dev_david

  enable_tuva_run_log: false # if true, will create metadata.tuva_invocations and log details about each run/test.

  pqi_enabled: true
  tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'

# Default dbt settings
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["dbt_doc_blocks"]
target-path: "target"

clean-targets:
    - "target"
    - "dbt_packages"
  