default:
  target: dev
  outputs:
    dev:
      type: fabric
      host: "{{ env_var('DBT_FABRIC_CI_HOST') }}"
      database: "{{ env_var('DBT_FABRIC_CI_DATABASE') }}"
      schema: "{{ env_var('DBT_FABRIC_CI_SCHEMA') }}"
      authentication: ServicePrincipal
      driver: ODBC Driver 18 for SQL Server
      client_id: "{{ env_var('DBT_FABRIC_SERVICE_PRINCIPAL_ID') }}"
      client_secret: "{{ env_var('DBT_FABRIC_SERVICE_PRINCIPAL_SECRET') }}"
      tenant_id: "{{ env_var('DBT_FABRIC_TENANT_ID') }}"
      threads: 8
