default:
  target: ci
  outputs:
    ci:
      type: fabric
      driver: ODBC Driver 18 for SQL Server
      authentication: ActiveDirectoryServicePrincipal
      server: "{{ env_var('DBT_FABRIC_CI_SERVER') }}"
      database: "{{ env_var('DBT_FABRIC_CI_DATABASE') }}"
      schema: "{{ env_var('DBT_FABRIC_CI_SCHEMA') }}"
      client_id: "{{ env_var('DBT_FABRIC_CI_CLIENT_ID') }}"
      client_secret: "{{ env_var('DBT_FABRIC_CI_CLIENT_SECRET') }}"
      tenant_id: "{{ env_var('DBT_FABRIC_CI_TENANT_ID') }}"
      encrypt: True
      trust_cert: False
      login_timeout: 30
      threads: 4