[[redirects]]
  from = "/blog"
  to = "https://tuva-blog.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://tuva-blog.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/home.css"
  to = "https://tuva-blog.netlify.app/home.css"
  status = 200
  force = true

[[redirects]]
  from = "/article.css"
  to = "https://tuva-blog.netlify.app/article.css"
  status = 200
  force = true

[[redirects]]
  from = "/search.json"
  to = "https://tuva-blog.netlify.app/search.json"
  status = 200
  force = true

[[redirects]]
  from = "/site_libs/*"
  to = "https://tuva-blog.netlify.app/site_libs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/img/blog/*"
  to = "https://tuva-blog.netlify.app/img/blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/img/tuva-favicon.ico"
  to = "https://tuva-blog.netlify.app/img/tuva-favicon.ico"
  status = 200
  force = true
