name: Auto-Assign Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  handle_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Assign issue to user
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const assignee = ['jansenpa', 'cocozuloaga']; // Assign to product leads for prioritization

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: [assignee]
            });
