
{{ config(materialized='view') }}

with conditions as (
select
    a.patient_id
,   b.condition_column_name
,   1 as condition_count
from {{ ref('chronic_conditions_long') }} a
inner join (select distinct condition, condition_column_name from {{ ref('chronic_conditions') }}) b
    on a.condition = b.condition
)

select 
    patient_id,
    case when acquired_hypothyroidism >= 1 then 1 else 0 end acquired_hypothyroidism,
    case when acute_myocardial_infarction >= 1 then 1 else 0 end acute_myocardial_infarction,
    case when adhd_conduct_disorders_and_hyperkinetic_syndrome >= 1 then 1 else 0 end adhd_conduct_disorders_and_hyperkinetic_syndrome,
    case when alcohol_use_disorders >= 1 then 1 else 0 end alcohol_use_disorders,
    case when alzheimers_disease >= 1 then 1 else 0 end alzheimers_disease,
    case when alzheimers_disease_and_related_disorders_or_senile_dementia >= 1 then 1 else 0 end alzheimers_disease_and_related_disorders_or_senile_dementia,
    case when anemia >= 1 then 1 else 0 end anemia,
    case when anxiety_disorders >= 1 then 1 else 0 end anxiety_disorders,
    case when asthma >= 1 then 1 else 0 end asthma,
    case when atrial_fibrillation >= 1 then 1 else 0 end atrial_fibrillation,
    case when autism_spectrum_disorders >= 1 then 1 else 0 end autism_spectrum_disorders,
    case when benign_prostatic_hyperplasia >= 1 then 1 else 0 end benign_prostatic_hyperplasia,
    case when bipolar_disorder >= 1 then 1 else 0 end bipolar_disorder,
    case when cataract >= 1 then 1 else 0 end cataract,
    case when cerebral_palsy >= 1 then 1 else 0 end cerebral_palsy,
    case when chronic_kidney_disease >= 1 then 1 else 0 end chronic_kidney_disease,
    case when chronic_obstructive_pulmonary_disease_and_bronchiectasis >= 1 then 1 else 0 end chronic_obstructive_pulmonary_disease_and_bronchiectasis,
    case when colorectal_cancer >= 1 then 1 else 0 end colorectal_cancer,
    case when cystic_fibrosis_and_other_metabolic_developmental_disorders >= 1 then 1 else 0 end cystic_fibrosis_and_other_metabolic_developmental_disorders,
    case when depression >= 1 then 1 else 0 end depression,
    case when diabetes >= 1 then 1 else 0 end diabetes,
    case when drug_use_disorders >= 1 then 1 else 0 end drug_use_disorders,
    case when endometrial_cancer >= 1 then 1 else 0 end endometrial_cancer,
    case when epilepsy >= 1 then 1 else 0 end epilepsy,
    case when female_male_breast_cancer >= 1 then 1 else 0 end female_male_breast_cancer,
    case when fibromyalgia_and_chronic_pain_and_fatigue >= 1 then 1 else 0 end fibromyalgia_and_chronic_pain_and_fatigue,
    case when glaucoma >= 1 then 1 else 0 end glaucoma,
    case when heart_failure >= 1 then 1 else 0 end heart_failure,
    case when hepatitis_a >= 1 then 1 else 0 end hepatitis_a,
    case when hepatitis_b >= 1 then 1 else 0 end hepatitis_b,
    case when hepatitis_c_acute >= 1 then 1 else 0 end hepatitis_c_acute,
    case when hepatitis_c_chronic >= 1 then 1 else 0 end hepatitis_c_chronic,
    case when hepatitis_c_unspecified >= 1 then 1 else 0 end hepatitis_c_unspecified,
    case when hepatitis_d >= 1 then 1 else 0 end hepatitis_d,
    case when hepatitis_e >= 1 then 1 else 0 end hepatitis_e,
    case when hip_pelvic_fracture >= 1 then 1 else 0 end hip_pelvic_fracture,
    case when human_immunodeficiency_virus_and_or_acquired_immunodeficiency_syndrome_hiv_aids >= 1 then 1 else 0 end human_immunodeficiency_virus_and_or_acquired_immunodeficiency_syndrome_hiv_aids,
    case when hyperlipidemia >= 1 then 1 else 0 end hyperlipidemia,
    case when hypertension >= 1 then 1 else 0 end hypertension,
    case when intellectual_disabilities_and_related_conditions >= 1 then 1 else 0 end intellectual_disabilities_and_related_conditions,
    case when ischemic_heart_disease >= 1 then 1 else 0 end ischemic_heart_disease,
    case when learning_disabilities >= 1 then 1 else 0 end learning_disabilities,
    case when leukemias_and_lymphomas >= 1 then 1 else 0 end leukemias_and_lymphomas,
    case when liver_disease_cirrhosis_and_other_liver_conditions_except_viral_hepatitis >= 1 then 1 else 0 end liver_disease_cirrhosis_and_other_liver_conditions_except_viral_hepatitis,
    case when lung_cancer >= 1 then 1 else 0 end lung_cancer,
    case when migraine_and_chronic_headache >= 1 then 1 else 0 end migraine_and_chronic_headache,
    case when mobility_impairments >= 1 then 1 else 0 end mobility_impairments,
    case when multiple_sclerosis_and_transverse_myelitis >= 1 then 1 else 0 end multiple_sclerosis_and_transverse_myelitis,
    case when muscular_dystrophy >= 1 then 1 else 0 end muscular_dystrophy,
    case when obesity >= 1 then 1 else 0 end obesity,
    case when opioid_use_disorder >= 1 then 1 else 0 end opioid_use_disorder,
    case when osteoporosis >= 1 then 1 else 0 end osteoporosis,
    case when other_developmental_delays >= 1 then 1 else 0 end other_developmental_delays,
    case when peripheral_vascular_disease_pvd >= 1 then 1 else 0 end peripheral_vascular_disease_pvd,
    case when personality_disorders >= 1 then 1 else 0 end personality_disorders,
    case when post_traumatic_stress_disorder_ptsd >= 1 then 1 else 0 end post_traumatic_stress_disorder_ptsd,
    case when pressure_and_chronic_ulcers >= 1 then 1 else 0 end pressure_and_chronic_ulcers,
    case when prostate_cancer >= 1 then 1 else 0 end prostate_cancer,
    case when rheumatoid_arthritis__osteoarthritis_ra_oa >= 1 then 1 else 0 end rheumatoid_arthritis__osteoarthritis_ra_oa,
    case when schizophrenia >= 1 then 1 else 0 end schizophrenia,
    case when schizophrenia_and_other_psychotic_disorders >= 1 then 1 else 0 end schizophrenia_and_other_psychotic_disorders,
    case when sensory_blindness_and_visual_impairment >= 1 then 1 else 0 end sensory_blindness_and_visual_impairment,
    case when sensory_deafness_and_hearing_impairment >= 1 then 1 else 0 end sensory_deafness_and_hearing_impairment,
    case when sickle_cell_disease >= 1 then 1 else 0 end sickle_cell_disease,
    case when spina_bifida_and_other_congenital_anomalies_of_the_nervous_system >= 1 then 1 else 0 end spina_bifida_and_other_congenital_anomalies_of_the_nervous_system,
    case when spinal_cord_injury >= 1 then 1 else 0 end spinal_cord_injury,
    case when stroke_transient_ischemic_attack >= 1 then 1 else 0 end stroke_transient_ischemic_attack,
    case when tobacco_use >= 1 then 1 else 0 end tobacco_use,
    case when traumatic_brain_injury_and_nonpsychotic_mental_disorders_due_to_brain_damage >= 1 then 1 else 0 end traumatic_brain_injury_and_nonpsychotic_mental_disorders_due_to_brain_damage
from conditions
pivot
(
    sum(condition_count)
    for condition_column_name in
    (
        'acquired_hypothyroidism',
        'acute_myocardial_infarction',
        'adhd_conduct_disorders_and_hyperkinetic_syndrome',
        'alcohol_use_disorders',
        'alzheimers_disease',
        'alzheimers_disease_and_related_disorders_or_senile_dementia',
        'anemia',
        'anxiety_disorders',
        'asthma',
        'atrial_fibrillation',
        'autism_spectrum_disorders',
        'benign_prostatic_hyperplasia',
        'bipolar_disorder',
        'cataract',
        'cerebral_palsy',
        'chronic_kidney_disease',
        'chronic_obstructive_pulmonary_disease_and_bronchiectasis',
        'colorectal_cancer',
        'cystic_fibrosis_and_other_metabolic_developmental_disorders',
        'depression',
        'diabetes',
        'drug_use_disorders',
        'endometrial_cancer',
        'epilepsy',
        'female_male_breast_cancer',
        'fibromyalgia_and_chronic_pain_and_fatigue',
        'glaucoma',
        'heart_failure',
        'hepatitis_a',
        'hepatitis_b',
        'hepatitis_c_acute',
        'hepatitis_c_chronic',
        'hepatitis_c_unspecified',
        'hepatitis_d',
        'hepatitis_e',
        'hip_pelvic_fracture',
        'human_immunodeficiency_virus_and_or_acquired_immunodeficiency_syndrome_hiv_aids',
        'hyperlipidemia',
        'hypertension',
        'intellectual_disabilities_and_related_conditions',
        'ischemic_heart_disease',
        'learning_disabilities',
        'leukemias_and_lymphomas',
        'liver_disease_cirrhosis_and_other_liver_conditions_except_viral_hepatitis',
        'lung_cancer',
        'migraine_and_chronic_headache',
        'mobility_impairments',
        'multiple_sclerosis_and_transverse_myelitis',
        'muscular_dystrophy',
        'obesity',
        'opioid_use_disorder',
        'osteoporosis',
        'other_developmental_delays',
        'peripheral_vascular_disease_pvd',
        'personality_disorders',
        'post_traumatic_stress_disorder_ptsd',
        'pressure_and_chronic_ulcers',
        'prostate_cancer',
        'rheumatoid_arthritis__osteoarthritis_ra_oa',
        'schizophrenia',
        'schizophrenia_and_other_psychotic_disorders',
        'sensory_blindness_and_visual_impairment',
        'sensory_deafness_and_hearing_impairment',
        'sickle_cell_disease',
        'spina_bifida_and_other_congenital_anomalies_of_the_nervous_system',
        'spinal_cord_injury',
        'stroke_transient_ischemic_attack',
        'tobacco_use',
        'traumatic_brain_injury_and_nonpsychotic_mental_disorders_due_to_brain_damage'
    )) 
as pvt (
    patient_id,
    acquired_hypothyroidism,
    acute_myocardial_infarction,
    adhd_conduct_disorders_and_hyperkinetic_syndrome,
    alcohol_use_disorders,
    alzheimers_disease,
    alzheimers_disease_and_related_disorders_or_senile_dementia,
    anemia,
    anxiety_disorders,
    asthma,
    atrial_fibrillation,
    autism_spectrum_disorders,
    benign_prostatic_hyperplasia,
    bipolar_disorder,
    cataract,
    cerebral_palsy,
    chronic_kidney_disease,
    chronic_obstructive_pulmonary_disease_and_bronchiectasis,
    colorectal_cancer,
    cystic_fibrosis_and_other_metabolic_developmental_disorders,
    depression,
    diabetes,
    drug_use_disorders,
    endometrial_cancer,
    epilepsy,
    female_male_breast_cancer,
    fibromyalgia_and_chronic_pain_and_fatigue,
    glaucoma,
    heart_failure,
    hepatitis_a,
    hepatitis_b,
    hepatitis_c_acute,
    hepatitis_c_chronic,
    hepatitis_c_unspecified,
    hepatitis_d,
    hepatitis_e,
    hip_pelvic_fracture,
    human_immunodeficiency_virus_and_or_acquired_immunodeficiency_syndrome_hiv_aids,
    hyperlipidemia,
    hypertension,
    intellectual_disabilities_and_related_conditions,
    ischemic_heart_disease,
    learning_disabilities,
    leukemias_and_lymphomas,
    liver_disease_cirrhosis_and_other_liver_conditions_except_viral_hepatitis,
    lung_cancer,
    migraine_and_chronic_headache,
    mobility_impairments,
    multiple_sclerosis_and_transverse_myelitis,
    muscular_dystrophy,
    obesity,
    opioid_use_disorder,
    osteoporosis,
    other_developmental_delays,
    peripheral_vascular_disease_pvd,
    personality_disorders,
    post_traumatic_stress_disorder_ptsd,
    pressure_and_chronic_ulcers,
    prostate_cancer,
    rheumatoid_arthritis__osteoarthritis_ra_oa,
    schizophrenia,
    schizophrenia_and_other_psychotic_disorders,
    sensory_blindness_and_visual_impairment,
    sensory_deafness_and_hearing_impairment,
    sickle_cell_disease,
    spina_bifida_and_other_congenital_anomalies_of_the_nervous_system,
    spinal_cord_injury,
    stroke_transient_ischemic_attack,
    tobacco_use,
    traumatic_brain_injury_and_nonpsychotic_mental_disorders_due_to_brain_damage
    )